name = "replicationstudyjuliam2econ"
uuid = "d986416c-f163-4c97-9f89-77b32385f861"
authors = ["Mona Lisa <anirudh.bharadwaj@sciencespo.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
